# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2417a17319d409e8521108a43b761d99829b0624b53e8df5d40c4c70c57dc0960adeb10f40264282471001f8dc2e26af833728daa77b0855b93444a24ea75a4f

test:
  secret_key_base: 5d7e2d9920c538c947c599499dc290a8941250eeb209611ff9f321fdbbc21d9e592cad4981603cdf3bd1959c270b25858a10dc03808cc152909d6ad2bfb9a6fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
